# Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([(1,2,3), (4,5,6)])

In [3]:
print(a)

[[1 2 3]
 [4 5 6]]


## Numpy Operations

In [11]:
print(a)               #This is the array we are working with...
print(a.ndim)          #Prints the dimension of array
print(a.itemsize)      #Prints the size of the array in memory bytes
print(a.dtype)         #Prints the datatype of the array
print(a.size)          #Prints the number of elements present in array
print(a.shape)         #Prints the shape of the array

[[1 2 3]
 [4 5 6]]
2
4
int32
6
(2, 3)


In [13]:
print(a)                         #Original array
print(a.reshape(3,2))            #Prints the reshaped array depending on the new rows and columns
print(a[0][2]) #print(a[0,2])    #Prints the element at that index of array

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
3


In [20]:
print(a)
print(a[0:,2])                 #':' is the slicing operator in python 

[[1 2 3]
 [4 5 6]]
[3 6]


In [22]:
a=np.linspace(1, 3, 10)         #Creates a new numpy array of 10 elements from [1,3] even-spaced from each other
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [25]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
print(a.min())
print(a.max())
print(a.sum())
print(np.sqrt(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
45
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


## Stacking

In [28]:
a=np.array([(1,2),(7,8)])
b=np.array([(3,4),(5,6)])
print(a)
print("--------")
print(b)

[[1 2]
 [7 8]]
--------
[[3 4]
 [5 6]]


In [30]:
print(np.vstack((a,b)))

[[1 2]
 [7 8]
 [3 4]
 [5 6]]


In [31]:
print(np.hstack((a,b)))

[[1 2 3 4]
 [7 8 5 6]]
